# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cold Sun
email:
description: This is a website created with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaz-yamada.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social icons and sharing options
twitter_username:
github_username:
linkedin_username:
google_plus_username:
facebook_username:
dribbble_username:

social:
  - name: Twitter
    icon: twitter
    username:
    url:
    share: true

  - name: Facebook
    icon: facebook
    username:
    url:
    share: true

  - name: GitHub
    icon: github
    username:
    url:
    share: false

  - name: LinkedIn
    icon: linkedin
    username:
    url:
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    share: true

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    share: false

author:
  name   : "Your Name"
  avatar :
  bio    : "Biography goes here."
  email  : # optional
  uri    : "http://example.com"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
